name: rechoice_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  google_fonts: ^6.3.3
  http: ^1.6.0
  firebase_auth: ^6.1.3
  google_sign_in: ^6.1.0
  cloud_firestore: ^6.1.1
  firebase_database: ^12.1.1
  firebase_storage: ^13.0.5
  provider: ^6.1.5+1
  image_picker: ^1.2.1
  hive_ce: ^2.16.0
  path: ^1.9.1
  hive_ce_flutter: ^2.3.3
  path_provider: ^2.1.5
  csv: ^6.0.0
  equatable: ^2.0.7
  synchronized: ^3.4.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/electronics/
    - assets/images/fashion/
    - assets/images/personalCare/
    - assets/images/books/
    - assets/images/home-living/
